// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/blog/[slug]/[file].ts";
import * as $2 from "./routes/blog/[slug]/index.tsx";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/MailerLite.tsx";
import * as $$1 from "./islands/Slider.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/blog/[slug]/[file].ts": $1,
    "./routes/blog/[slug]/index.tsx": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/MailerLite.tsx": $$0,
    "./islands/Slider.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
